<?php
/**
 * Created by PhpStorm.
 * User: T.Ron
 * Date: 27/04/2018
 * Time: 23:58
 */

class P_DeviseClass Extends Objet{
    //put your code here
    public $db,$D_Intitule
    ,$D_Format
    ,$D_Cours
    ,$D_CoursP
    ,$D_Monnaie
    ,$D_SousMonnaie
    ,$D_CodeISO
    ,$D_Sigle
    ,$D_Mode
    ,$N_DeviseCot
    ,$D_CoursClot
    ,$D_AncDate
    ,$D_AncCours
    ,$D_AncMode
    ,$N_DeviseAncCot
    ,$D_CodeRemise
    ,$D_Euro
    ,$D_CodeISONum
    ,$cbIndice
    ,$cbMarq;

    public $lien = 'pdevise';
    public $table = 'P_DEVISE';

    function __construct($id,$db=null) {
        parent::__construct($this->table, $id,'cbMarq',$db);
        $this->data = $this->getApiJson("/cbMarq=$id");
        if(sizeof($this->data)>0) {
            $this->D_Intitule = $this->data[0]->D_Intitule;
            $this->D_Format = $this->data[0]->D_Format;
            $this->D_Cours = $this->data[0]->D_Cours;
            $this->D_CoursP = $this->data[0]->D_CoursP;
            $this->D_Monnaie = $this->data[0]->D_Monnaie;
            $this->D_SousMonnaie = $this->data[0]->D_SousMonnaie;
            $this->D_CodeISO = $this->data[0]->D_CodeISO;
            $this->D_Sigle = $this->data[0]->D_Sigle;
            $this->D_Mode = $this->data[0]->D_Mode;
            $this->N_DeviseCot = $this->data[0]->N_DeviseCot;
            $this->D_CoursClot = $this->data[0]->D_CoursClot;
            $this->D_AncDate = $this->data[0]->D_AncDate;
            $this->D_AncCours = $this->data[0]->D_AncCours;
            $this->D_AncMode = $this->data[0]->D_AncMode;
            $this->N_DeviseAncCot = $this->data[0]->N_DeviseAncCot;
            $this->D_CodeRemise = $this->data[0]->D_CodeRemise;
            $this->D_Euro = $this->data[0]->D_Euro;
            $this->D_CodeISONum = $this->data[0]->D_CodeISONum;
            $this->cbIndice = $this->data[0]->cbIndice;
            $this->cbMarq = $this->data[0]->cbMarq;
        }
    }

    public function afficheSelect($rows, $value,$code="cbIndice",$intitule="D_Intitule")
    {

        $html="";
        foreach ($rows as $row) {
            $html = $html ."<option value='{$row->cbIndice}'";
            if ($value == $row->cbIndice)
                $html." selected";
            $html = $html.">{$row->D_Intitule}</option>";
        }
        echo $html;
//        return parent::afficheSelect($rows, $value,$code,$intitule); // TODO: Change the autogenerated stub
    }

    public function __toString() {
        return "";
    }

}