<?php
/**
 * Created by PhpStorm.
 * User: T.Ron
 * Date: 27/04/2018
 * Time: 23:58
 */

class P_UniteClass Extends Objet{
    //put your code here
    public $db,$U_Intitule
    ,$U_Correspondance
    ,$U_NbUnite
    ,$U_UniteTemps
    ,$cbIndice
    ,$cbMarq
    ;

    public $lien = 'punite';
    public $table = 'P_UNITE';

    function __construct($id,$db=null) {
        parent::__construct($this->table, $id,'cbMarq',$db);
        $this->data = $this->getApiJson("/cbMarq=$id");
        if(sizeof($this->data)>0) {
            $this->U_Intitule = $this->data[0]->U_Intitule;
            $this->U_Correspondance = $this->data[0]->U_Correspondance;
            $this->U_NbUnite = $this->data[0]->U_NbUnite;
            $this->U_UniteTemps = $this->data[0]->U_UniteTemps;
            $this->cbIndice = $this->data[0]->cbIndice;
            $this->cbMarq = $this->data[0]->cbMarq;
        }
    }

    public function afficheSelect($rows,$value, $code="cbIndice",$intitule="U_Intitule")
    {
        $html="";
        foreach ($rows as $row) {
            $html = $html ."<option value='{$row->cbIndice}'";
            if ($value == $row->cbIndice)
                $html." selected";
            $html = $html.">{$row->U_Intitule}</option>";
        }
        echo $html;
//        return parent::afficheSelect($rows,$value,$code,$intitule); // TODO: Change the autogenerated stub
    }

    public function __toString() {
        return "";
    }

}